# Generated by Django 3.2.5 on 2021-07-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20210713_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attedance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
